datasource:
  url: jdbc:mysql://localhost:3306/your_database?useSSL=false&serverTimezone=UTC
  username: root
  password: computer
  driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect